spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.dts.scheduler: DEBUG
    org.springframework.security: INFO
    org.springframework.kafka: INFO
